// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.616.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;
using static TerraFX.Interop.DirectX.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP = (1 << D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_EIGHTTAP),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP_SMOOTH"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP_SMOOTH = (1 << D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_EIGHTTAP_SMOOTH),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP_SHARP"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_EIGHTTAP_SHARP = (1 << D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_EIGHTTAP_SHARP),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_BILINEAR"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_BILINEAR = (1 << D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_BILINEAR),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_SWITCHABLE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAG_SWITCHABLE = (1 << D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_SWITCHABLE),
}
