// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION"]/*' />
public enum D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION
{
    /// <include file='D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_FULL_PIXEL"]/*' />
    D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_FULL_PIXEL = 0,

    /// <include file='D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_HALF_PIXEL"]/*' />
    D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_HALF_PIXEL = 1,

    /// <include file='D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_QUARTER_PIXEL"]/*' />
    D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION_QUARTER_PIXEL = 2,
}
