// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.616.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE"]/*' />
public enum D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_DISABLED"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_DISABLED = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_Q"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_Q = 1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_V"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_V = 2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_H"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_H = 3,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_U"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_U = 4,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_V"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_V = 5,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_REF_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_REF_FRAME = 6,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_SKIP"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_SKIP = 7,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_GLOBALMV"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_GLOBALMV = 8,
}
