// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.616.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_QUANTIZATION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_QUANTIZATION = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_QUANTIZATION_DELTA"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_QUANTIZATION_DELTA = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_LOOP_FILTER"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_LOOP_FILTER = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_LOOP_FILTER_DELTA"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_LOOP_FILTER_DELTA = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_CDEF_DATA"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_CDEF_DATA = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_CONTEXT_UPDATE_TILE_ID"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_CONTEXT_UPDATE_TILE_ID = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_COMPOUND_PREDICTION_MODE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_COMPOUND_PREDICTION_MODE = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_PRIMARY_REF_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_PRIMARY_REF_FRAME = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_REFERENCE_INDICES"]/*' />
    D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAG_REFERENCE_INDICES = 0x100,
}
