// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE"]/*' />
public enum D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_4x4"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_4x4 = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_8x8"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_8x8 = 1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_16x16"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_16x16 = 2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_32x32"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_32x32 = 3,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_64x64"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE_64x64 = 4,
}
