// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.611.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;
using static TerraFX.Interop.DirectX.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_KEY_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_KEY_FRAME = (1 << D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_KEY_FRAME),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_INTER_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_INTER_FRAME = (1 << D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_INTER_FRAME),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_INTRA_ONLY_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_INTRA_ONLY_FRAME = (1 << D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_INTRA_ONLY_FRAME),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_SWITCH_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAG_SWITCH_FRAME = (1 << D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_SWITCH_FRAME),
}
