// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/d3d12video.h in the Windows SDK for Windows 10.0.22000.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO"]/*' />
public enum D3D12_FEATURE_VIDEO
{
    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_SUPPORT"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_SUPPORT = 0,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_PROFILES"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_PROFILES = 1,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_FORMATS"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_FORMATS = 2,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_CONVERSION_SUPPORT"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_CONVERSION_SUPPORT = 3,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESS_SUPPORT"]/*' />
    D3D12_FEATURE_VIDEO_PROCESS_SUPPORT = 5,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESS_MAX_INPUT_STREAMS"]/*' />
    D3D12_FEATURE_VIDEO_PROCESS_MAX_INPUT_STREAMS = 6,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESS_REFERENCE_INFO"]/*' />
    D3D12_FEATURE_VIDEO_PROCESS_REFERENCE_INFO = 7,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODER_HEAP_SIZE"]/*' />
    D3D12_FEATURE_VIDEO_DECODER_HEAP_SIZE = 8,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESSOR_SIZE"]/*' />
    D3D12_FEATURE_VIDEO_PROCESSOR_SIZE = 9,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_PROFILE_COUNT"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_PROFILE_COUNT = 10,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_FORMAT_COUNT"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_FORMAT_COUNT = 11,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_ARCHITECTURE"]/*' />
    D3D12_FEATURE_VIDEO_ARCHITECTURE = 17,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_HISTOGRAM"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_HISTOGRAM = 18,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_FEATURE_AREA_SUPPORT"]/*' />
    D3D12_FEATURE_VIDEO_FEATURE_AREA_SUPPORT = 19,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR"]/*' />
    D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR = 20,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR_SIZE"]/*' />
    D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR_SIZE = 21,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_COUNT"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_COUNT = 22,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMANDS"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMANDS = 23,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_PARAMETER_COUNT"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_PARAMETER_COUNT = 24,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_PARAMETERS"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_PARAMETERS = 25,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_SUPPORT"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_SUPPORT = 26,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_SIZE"]/*' />
    D3D12_FEATURE_VIDEO_EXTENSION_COMMAND_SIZE = 27,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODE_PROTECTED_RESOURCES"]/*' />
    D3D12_FEATURE_VIDEO_DECODE_PROTECTED_RESOURCES = 28,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESS_PROTECTED_RESOURCES"]/*' />
    D3D12_FEATURE_VIDEO_PROCESS_PROTECTED_RESOURCES = 29,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR_PROTECTED_RESOURCES"]/*' />
    D3D12_FEATURE_VIDEO_MOTION_ESTIMATOR_PROTECTED_RESOURCES = 30,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_DECODER_HEAP_SIZE1"]/*' />
    D3D12_FEATURE_VIDEO_DECODER_HEAP_SIZE1 = 31,

    /// <include file='D3D12_FEATURE_VIDEO.xml' path='doc/member[@name="D3D12_FEATURE_VIDEO.D3D12_FEATURE_VIDEO_PROCESSOR_SIZE1"]/*' />
    D3D12_FEATURE_VIDEO_PROCESSOR_SIZE1 = 32,
}
