// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_128x128_SUPERBLOCK"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_128x128_SUPERBLOCK = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FILTER_INTRA"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FILTER_INTRA = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTRA_EDGE_FILTER"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTRA_EDGE_FILTER = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTERINTRA_COMPOUND"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTERINTRA_COMPOUND = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_MASKED_COMPOUND"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_MASKED_COMPOUND = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_WARPED_MOTION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_WARPED_MOTION = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_DUAL_FILTER"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_DUAL_FILTER = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_JNT_COMP"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_JNT_COMP = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FORCED_INTEGER_MOTION_VECTORS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FORCED_INTEGER_MOTION_VECTORS = 0x100,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_SUPER_RESOLUTION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_SUPER_RESOLUTION = 0x200,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_LOOP_RESTORATION_FILTER"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_LOOP_RESTORATION_FILTER = 0x400,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_PALETTE_ENCODING"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_PALETTE_ENCODING = 0x800,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_CDEF_FILTERING"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_CDEF_FILTERING = 0x1000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTRA_BLOCK_COPY"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_INTRA_BLOCK_COPY = 0x2000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FRAME_REFERENCE_MOTION_VECTORS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_FRAME_REFERENCE_MOTION_VECTORS = 0x4000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_ORDER_HINT_TOOLS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_ORDER_HINT_TOOLS = 0x8000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_AUTO_SEGMENTATION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_AUTO_SEGMENTATION = 0x10000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_CUSTOM_SEGMENTATION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_CUSTOM_SEGMENTATION = 0x20000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_LOOP_FILTER_DELTAS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_LOOP_FILTER_DELTAS = 0x40000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_QUANTIZATION_DELTAS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_QUANTIZATION_DELTAS = 0x80000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_QUANTIZATION_MATRIX"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_QUANTIZATION_MATRIX = 0x100000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_REDUCED_TX_SET"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_REDUCED_TX_SET = 0x200000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_MOTION_MODE_SWITCHABLE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_MOTION_MODE_SWITCHABLE = 0x400000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_ALLOW_HIGH_PRECISION_MV"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_ALLOW_HIGH_PRECISION_MV = 0x800000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_SKIP_MODE_PRESENT"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_SKIP_MODE_PRESENT = 0x1000000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_DELTA_LF_PARAMS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAG_DELTA_LF_PARAMS = 0x2000000,
}
