// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.618.5
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_ERROR_RESILIENT_MODE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_ERROR_RESILIENT_MODE = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_CDF_UPDATE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_CDF_UPDATE = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_PALETTE_ENCODING"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_PALETTE_ENCODING = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_SKIP_MODE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_SKIP_MODE = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FRAME_REFERENCE_MOTION_VECTORS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FRAME_REFERENCE_MOTION_VECTORS = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FORCE_INTEGER_MOTION_VECTORS"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FORCE_INTEGER_MOTION_VECTORS = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_INTRA_BLOCK_COPY"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_INTRA_BLOCK_COPY = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_USE_SUPER_RESOLUTION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_USE_SUPER_RESOLUTION = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_FRAME_END_UPDATE_CDF"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_FRAME_END_UPDATE_CDF = 0x100,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_AUTO"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_AUTO = 0x200,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_CUSTOM"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_CUSTOM = 0x400,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_WARPED_MOTION"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_WARPED_MOTION = 0x800,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_REDUCED_TX_SET"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_REDUCED_TX_SET = 0x1000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_MOTION_MODE_SWITCHABLE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_MOTION_MODE_SWITCHABLE = 0x2000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_HIGH_PRECISION_MV"]/*' />
    D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_HIGH_PRECISION_MV = 0x4000,
}
