// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

using System;
using static TerraFX.Interop.DirectX.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS"]/*' />
[Flags]
public enum D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_DISABLED"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_DISABLED = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_DISABLED),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_Q"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_Q = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_Q),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_Y_V"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_Y_V = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_V),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_Y_H"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_Y_H = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_Y_H),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_U"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_U = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_U),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_V"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_LF_V = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_LF_V),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_REF_FRAME"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_REF_FRAME = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_REF_FRAME),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_SKIP"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_SKIP = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_SKIP),

    /// <include file='D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_GLOBALMV"]/*' />
    D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAG_ALT_GLOBALMV = (1 << D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_ALT_GLOBALMV),
}
