// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.618.5
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS"]/*' />
public enum D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS
{
    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_NONE"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_NONE = 0,

    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_QP_MAP"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_QP_MAP = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_SATD_MAP"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_SATD_MAP = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_RC_BIT_ALLOCATION_MAP"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_RC_BIT_ALLOCATION_MAP = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_FRAME_PSNR"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_FRAME_PSNR = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_SUBREGIONS_PSNR"]/*' />
    D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAG_SUBREGIONS_PSNR = 0x10,
}
