// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from D3D12TokenizedProgramFormat.hpp in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY"]/*' />
public enum D3D10_SB_PRIMITIVE_TOPOLOGY
{
    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_UNDEFINED"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_UNDEFINED = 0,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_POINTLIST"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_POINTLIST = 1,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST = 2,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP = 3,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST = 4,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP = 5,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST_ADJ"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINELIST_ADJ = 10,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ = 11,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ = 12,

    /// <include file='D3D10_SB_PRIMITIVE_TOPOLOGY.xml' path='doc/member[@name="D3D10_SB_PRIMITIVE_TOPOLOGY.D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ"]/*' />
    D3D10_SB_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ = 13,
}
