// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from D3D12TokenizedProgramFormat.hpp in microsoft/DirectX-Headers tag v1.611.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION"]/*' />
public enum D3D10_SB_RESOURCE_DIMENSION
{
    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_UNKNOWN"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_UNKNOWN = 0,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_BUFFER"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_BUFFER = 1,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE1D"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE1D = 2,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE2D"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2D = 3,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMS"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMS = 4,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE3D"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE3D = 5,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBE"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBE = 6,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE1DARRAY"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE1DARRAY = 7,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DARRAY"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DARRAY = 8,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMSARRAY"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMSARRAY = 9,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBEARRAY"]/*' />
    D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBEARRAY = 10,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D11_SB_RESOURCE_DIMENSION_RAW_BUFFER"]/*' />
    D3D11_SB_RESOURCE_DIMENSION_RAW_BUFFER = 11,

    /// <include file='D3D10_SB_RESOURCE_DIMENSION.xml' path='doc/member[@name="D3D10_SB_RESOURCE_DIMENSION.D3D11_SB_RESOURCE_DIMENSION_STRUCTURED_BUFFER"]/*' />
    D3D11_SB_RESOURCE_DIMENSION_STRUCTURED_BUFFER = 12,
}
