// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from D3D12TokenizedProgramFormat.hpp in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE"]/*' />
public enum D3D10_SB_OPERAND_TYPE
{
    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_TEMP"]/*' />
    D3D10_SB_OPERAND_TYPE_TEMP = 0,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_INPUT"]/*' />
    D3D10_SB_OPERAND_TYPE_INPUT = 1,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_OUTPUT"]/*' />
    D3D10_SB_OPERAND_TYPE_OUTPUT = 2,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_INDEXABLE_TEMP"]/*' />
    D3D10_SB_OPERAND_TYPE_INDEXABLE_TEMP = 3,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_IMMEDIATE32"]/*' />
    D3D10_SB_OPERAND_TYPE_IMMEDIATE32 = 4,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_IMMEDIATE64"]/*' />
    D3D10_SB_OPERAND_TYPE_IMMEDIATE64 = 5,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_SAMPLER"]/*' />
    D3D10_SB_OPERAND_TYPE_SAMPLER = 6,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_RESOURCE"]/*' />
    D3D10_SB_OPERAND_TYPE_RESOURCE = 7,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_CONSTANT_BUFFER"]/*' />
    D3D10_SB_OPERAND_TYPE_CONSTANT_BUFFER = 8,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_IMMEDIATE_CONSTANT_BUFFER"]/*' />
    D3D10_SB_OPERAND_TYPE_IMMEDIATE_CONSTANT_BUFFER = 9,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_LABEL"]/*' />
    D3D10_SB_OPERAND_TYPE_LABEL = 10,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_INPUT_PRIMITIVEID"]/*' />
    D3D10_SB_OPERAND_TYPE_INPUT_PRIMITIVEID = 11,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_OUTPUT_DEPTH"]/*' />
    D3D10_SB_OPERAND_TYPE_OUTPUT_DEPTH = 12,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_NULL"]/*' />
    D3D10_SB_OPERAND_TYPE_NULL = 13,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_RASTERIZER"]/*' />
    D3D10_SB_OPERAND_TYPE_RASTERIZER = 14,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D10_SB_OPERAND_TYPE_OUTPUT_COVERAGE_MASK"]/*' />
    D3D10_SB_OPERAND_TYPE_OUTPUT_COVERAGE_MASK = 15,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_STREAM"]/*' />
    D3D11_SB_OPERAND_TYPE_STREAM = 16,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_FUNCTION_BODY"]/*' />
    D3D11_SB_OPERAND_TYPE_FUNCTION_BODY = 17,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_FUNCTION_TABLE"]/*' />
    D3D11_SB_OPERAND_TYPE_FUNCTION_TABLE = 18,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INTERFACE"]/*' />
    D3D11_SB_OPERAND_TYPE_INTERFACE = 19,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_FUNCTION_INPUT"]/*' />
    D3D11_SB_OPERAND_TYPE_FUNCTION_INPUT = 20,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_FUNCTION_OUTPUT"]/*' />
    D3D11_SB_OPERAND_TYPE_FUNCTION_OUTPUT = 21,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_OUTPUT_CONTROL_POINT_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_OUTPUT_CONTROL_POINT_ID = 22,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_FORK_INSTANCE_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_FORK_INSTANCE_ID = 23,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_JOIN_INSTANCE_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_JOIN_INSTANCE_ID = 24,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_CONTROL_POINT"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_CONTROL_POINT = 25,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_OUTPUT_CONTROL_POINT"]/*' />
    D3D11_SB_OPERAND_TYPE_OUTPUT_CONTROL_POINT = 26,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_PATCH_CONSTANT"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_PATCH_CONSTANT = 27,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_DOMAIN_POINT"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_DOMAIN_POINT = 28,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_THIS_POINTER"]/*' />
    D3D11_SB_OPERAND_TYPE_THIS_POINTER = 29,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_UNORDERED_ACCESS_VIEW"]/*' />
    D3D11_SB_OPERAND_TYPE_UNORDERED_ACCESS_VIEW = 30,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_THREAD_GROUP_SHARED_MEMORY"]/*' />
    D3D11_SB_OPERAND_TYPE_THREAD_GROUP_SHARED_MEMORY = 31,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID = 32,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_THREAD_GROUP_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_THREAD_GROUP_ID = 33,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID_IN_GROUP"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID_IN_GROUP = 34,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_COVERAGE_MASK"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_COVERAGE_MASK = 35,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID_IN_GROUP_FLATTENED"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_THREAD_ID_IN_GROUP_FLATTENED = 36,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INPUT_GS_INSTANCE_ID"]/*' />
    D3D11_SB_OPERAND_TYPE_INPUT_GS_INSTANCE_ID = 37,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_OUTPUT_DEPTH_GREATER_EQUAL"]/*' />
    D3D11_SB_OPERAND_TYPE_OUTPUT_DEPTH_GREATER_EQUAL = 38,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_OUTPUT_DEPTH_LESS_EQUAL"]/*' />
    D3D11_SB_OPERAND_TYPE_OUTPUT_DEPTH_LESS_EQUAL = 39,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_CYCLE_COUNTER"]/*' />
    D3D11_SB_OPERAND_TYPE_CYCLE_COUNTER = 40,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_OUTPUT_STENCIL_REF"]/*' />
    D3D11_SB_OPERAND_TYPE_OUTPUT_STENCIL_REF = 41,

    /// <include file='D3D10_SB_OPERAND_TYPE.xml' path='doc/member[@name="D3D10_SB_OPERAND_TYPE.D3D11_SB_OPERAND_TYPE_INNER_COVERAGE"]/*' />
    D3D11_SB_OPERAND_TYPE_INNER_COVERAGE = 42,
}
