// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.5
// Original source is Copyright © Microsoft. Licensed under the MIT license

using static TerraFX.Interop.DirectX.D3D12_MARKER_API;

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP"]/*' />
public enum D3D12_AUTO_BREADCRUMB_OP
{
    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_SETMARKER"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_SETMARKER = D3D12_MARKER_API_SETMARKER,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_BEGINEVENT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_BEGINEVENT = D3D12_MARKER_API_BEGINEVENT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ENDEVENT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ENDEVENT = D3D12_MARKER_API_ENDEVENT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DRAWINSTANCED"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DRAWINSTANCED = D3D12_MARKER_API_DRAWINSTANCED,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DRAWINDEXEDINSTANCED"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DRAWINDEXEDINSTANCED = D3D12_MARKER_API_DRAWINDEXEDINSTANCED,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_EXECUTEINDIRECT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_EXECUTEINDIRECT = D3D12_MARKER_API_EXECUTEINDIRECT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DISPATCH"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DISPATCH = D3D12_MARKER_API_DISPATCH,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_COPYBUFFERREGION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_COPYBUFFERREGION = D3D12_MARKER_API_COPYBUFFERREGION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_COPYTEXTUREREGION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_COPYTEXTUREREGION = D3D12_MARKER_API_COPYTEXTUREREGION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_COPYRESOURCE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_COPYRESOURCE = D3D12_MARKER_API_COPYRESOURCE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_COPYTILES"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_COPYTILES = D3D12_MARKER_API_COPYTILES,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCE = D3D12_MARKER_API_RESOLVESUBRESOURCE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_CLEARRENDERTARGETVIEW"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_CLEARRENDERTARGETVIEW = D3D12_MARKER_API_CLEARRENDERTARGETVIEW,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_CLEARUNORDEREDACCESSVIEW"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_CLEARUNORDEREDACCESSVIEW = D3D12_MARKER_API_CLEARUNORDEREDACCESSVIEW,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_CLEARDEPTHSTENCILVIEW"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_CLEARDEPTHSTENCILVIEW = D3D12_MARKER_API_CLEARDEPTHSTENCILVIEW,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOURCEBARRIER"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOURCEBARRIER = D3D12_MARKER_API_RESOURCEBARRIER,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_EXECUTEBUNDLE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_EXECUTEBUNDLE = D3D12_MARKER_API_EXECUTEBUNDLE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_PRESENT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_PRESENT = D3D12_MARKER_API_PRESENT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVEQUERYDATA"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVEQUERYDATA = D3D12_MARKER_API_RESOLVEQUERYDATA,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_BEGINSUBMISSION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_BEGINSUBMISSION = D3D12_MARKER_API_BEGINSUBMISSION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ENDSUBMISSION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ENDSUBMISSION = D3D12_MARKER_API_ENDSUBMISSION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME = D3D12_MARKER_API_DECODEFRAME,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES = D3D12_MARKER_API_PROCESSFRAMES,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT = D3D12_MARKER_API_ATOMICCOPYBUFFERUINT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT64"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ATOMICCOPYBUFFERUINT64 = D3D12_MARKER_API_ATOMICCOPYBUFFERUINT64,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCEREGION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVESUBRESOURCEREGION = D3D12_MARKER_API_RESOLVESUBRESOURCEREGION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_WRITEBUFFERIMMEDIATE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_WRITEBUFFERIMMEDIATE = D3D12_MARKER_API_WRITEBUFFERIMMEDIATE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME1"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME1 = D3D12_MARKER_API_DECODEFRAME1,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_SETPROTECTEDRESOURCESESSION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_SETPROTECTEDRESOURCESESSION = D3D12_MARKER_API_SETPROTECTEDRESOURCESESSION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME2"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DECODEFRAME2 = D3D12_MARKER_API_DECODEFRAME2,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES1"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES1 = D3D12_MARKER_API_PROCESSFRAMES1,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_BUILDRAYTRACINGACCELERATIONSTRUCTURE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_BUILDRAYTRACINGACCELERATIONSTRUCTURE = D3D12_MARKER_API_BUILDRAYTRACINGACCELERATIONSTRUCTURE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO = D3D12_MARKER_API_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_COPYRAYTRACINGACCELERATIONSTRUCTURE"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_COPYRAYTRACINGACCELERATIONSTRUCTURE = D3D12_MARKER_API_COPYRAYTRACINGACCELERATIONSTRUCTURE,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DISPATCHRAYS"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DISPATCHRAYS = D3D12_MARKER_API_DISPATCHRAYS,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_INITIALIZEMETACOMMAND"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_INITIALIZEMETACOMMAND = D3D12_MARKER_API_INITIALIZEMETACOMMAND,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_EXECUTEMETACOMMAND"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_EXECUTEMETACOMMAND = D3D12_MARKER_API_EXECUTEMETACOMMAND,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ESTIMATEMOTION"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ESTIMATEMOTION = D3D12_MARKER_API_ESTIMATEMOTION,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVEMOTIONVECTORHEAP"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVEMOTIONVECTORHEAP = D3D12_MARKER_API_RESOLVEMOTIONVECTORHEAP,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_SETPIPELINESTATE1"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_SETPIPELINESTATE1 = D3D12_MARKER_API_SETPIPELINESTATE1,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_INITIALIZEEXTENSIONCOMMAND"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_INITIALIZEEXTENSIONCOMMAND = D3D12_MARKER_API_INITIALIZEEXTENSIONCOMMAND,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_EXECUTEEXTENSIONCOMMAND"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_EXECUTEEXTENSIONCOMMAND = D3D12_MARKER_API_EXECUTEEXTENSIONCOMMAND,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DISPATCHMESH"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DISPATCHMESH = D3D12_MARKER_API_DISPATCHMESH,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ENCODEFRAME"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ENCODEFRAME = D3D12_MARKER_API_ENCODEFRAME,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVEENCODEROUTPUTMETADATA"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVEENCODEROUTPUTMETADATA = D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_BARRIER"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_BARRIER = D3D12_MARKER_API_BARRIER,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_BEGIN_COMMAND_LIST"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_BEGIN_COMMAND_LIST = D3D12_MARKER_API_BEGIN_COMMAND_LIST,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_DISPATCHGRAPH"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_DISPATCHGRAPH = D3D12_MARKER_API_DISPATCHGRAPH,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_SETPROGRAM"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_SETPROGRAM = D3D12_MARKER_API_SETPROGRAM,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_ENCODEFRAME1"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_ENCODEFRAME1 = D3D12_MARKER_API_ENCODEFRAME1,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVEENCODEROUTPUTMETADATA1"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVEENCODEROUTPUTMETADATA1 = D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA1,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_RESOLVEINPUTPARAMLAYOUT"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_RESOLVEINPUTPARAMLAYOUT = D3D12_MARKER_API_RESOLVEINPUTPARAMLAYOUT,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES2"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_PROCESSFRAMES2 = D3D12_MARKER_API_PROCESSFRAMES2,

    /// <include file='D3D12_AUTO_BREADCRUMB_OP.xml' path='doc/member[@name="D3D12_AUTO_BREADCRUMB_OP.D3D12_AUTO_BREADCRUMB_OP_SET_WORK_GRAPH_MAXIMUM_GPU_INPUT_RECORDS"]/*' />
    D3D12_AUTO_BREADCRUMB_OP_SET_WORK_GRAPH_MAXIMUM_GPU_INPUT_RECORDS = D3D12_MARKER_API_SET_WORK_GRAPH_MAXIMUM_GPU_INPUT_RECORDS,
}
