// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in Microsoft.Direct3D.D3D12 v1.600.10
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_BACKGROUND_PROCESSING_MODE.xml' path='doc/member[@name="D3D12_BACKGROUND_PROCESSING_MODE"]/*' />
public enum D3D12_BACKGROUND_PROCESSING_MODE
{
    /// <include file='D3D12_BACKGROUND_PROCESSING_MODE.xml' path='doc/member[@name="D3D12_BACKGROUND_PROCESSING_MODE.D3D12_BACKGROUND_PROCESSING_MODE_ALLOWED"]/*' />
    D3D12_BACKGROUND_PROCESSING_MODE_ALLOWED = 0,

    /// <include file='D3D12_BACKGROUND_PROCESSING_MODE.xml' path='doc/member[@name="D3D12_BACKGROUND_PROCESSING_MODE.D3D12_BACKGROUND_PROCESSING_MODE_ALLOW_INTRUSIVE_MEASUREMENTS"]/*' />
    D3D12_BACKGROUND_PROCESSING_MODE_ALLOW_INTRUSIVE_MEASUREMENTS = (D3D12_BACKGROUND_PROCESSING_MODE_ALLOWED + 1),

    /// <include file='D3D12_BACKGROUND_PROCESSING_MODE.xml' path='doc/member[@name="D3D12_BACKGROUND_PROCESSING_MODE.D3D12_BACKGROUND_PROCESSING_MODE_DISABLE_BACKGROUND_WORK"]/*' />
    D3D12_BACKGROUND_PROCESSING_MODE_DISABLE_BACKGROUND_WORK = (D3D12_BACKGROUND_PROCESSING_MODE_ALLOW_INTRUSIVE_MEASUREMENTS + 1),

    /// <include file='D3D12_BACKGROUND_PROCESSING_MODE.xml' path='doc/member[@name="D3D12_BACKGROUND_PROCESSING_MODE.D3D12_BACKGROUND_PROCESSING_MODE_DISABLE_PROFILING_BY_SYSTEM"]/*' />
    D3D12_BACKGROUND_PROCESSING_MODE_DISABLE_PROFILING_BY_SYSTEM = (D3D12_BACKGROUND_PROCESSING_MODE_DISABLE_BACKGROUND_WORK + 1),
}
