// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY"]/*' />
public enum D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY
{
    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_IDLE"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_IDLE = 0,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_DEFAULT"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_DEFAULT = 1,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_NORMAL_0"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_NORMAL_0 = 2,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_0"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_0 = 18,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_1"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_1 = 19,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_2"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_2 = 20,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_3"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_3 = 21,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_4"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_4 = 22,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_5"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_5 = 23,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_6"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_6 = 24,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_7"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_7 = 25,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_8"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_8 = 26,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_9"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_9 = 27,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_10"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_10 = 28,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_11"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_11 = 29,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_12"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_12 = 30,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_13"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_SOFT_REALTIME_13 = 31,

    /// <include file='D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.xml' path='doc/member[@name="D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY.D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_HARD_REALTIME"]/*' />
    D3D12_COMMAND_QUEUE_GLOBAL_PRIORITY_HARD_REALTIME = 32,
}
