// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT"]/*' />
public enum D3D12_BARRIER_LAYOUT
{
    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_UNDEFINED"]/*' />
    D3D12_BARRIER_LAYOUT_UNDEFINED = unchecked((int)(0xffffffff)),

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_COMMON = 0,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_PRESENT"]/*' />
    D3D12_BARRIER_LAYOUT_PRESENT = 0,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_GENERIC_READ = 1,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RENDER_TARGET"]/*' />
    D3D12_BARRIER_LAYOUT_RENDER_TARGET = 2,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_UNORDERED_ACCESS = 3,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_WRITE = 4,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ"]/*' />
    D3D12_BARRIER_LAYOUT_DEPTH_STENCIL_READ = 5,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_SHADER_RESOURCE = 6,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COPY_SOURCE = 7,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_COPY_DEST = 8,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_RESOLVE_SOURCE = 9,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_RESOLVE_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_RESOLVE_DEST = 10,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_SHADING_RATE_SOURCE = 11,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_DECODE_READ = 12,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_DECODE_WRITE = 13,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_READ = 14,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_PROCESS_WRITE = 15,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_READ = 16,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE"]/*' />
    D3D12_BARRIER_LAYOUT_VIDEO_ENCODE_WRITE = 17,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COMMON = 18,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ = 19,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_UNORDERED_ACCESS = 20,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_SHADER_RESOURCE = 21,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_SOURCE = 22,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_COPY_DEST = 23,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COMMON = 24,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_GENERIC_READ = 25,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_UNORDERED_ACCESS = 26,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_SHADER_RESOURCE = 27,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_SOURCE = 28,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST"]/*' />
    D3D12_BARRIER_LAYOUT_COMPUTE_QUEUE_COPY_DEST = 29,

    /// <include file='D3D12_BARRIER_LAYOUT.xml' path='doc/member[@name="D3D12_BARRIER_LAYOUT.D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ_COMPUTE_QUEUE_ACCESSIBLE"]/*' />
    D3D12_BARRIER_LAYOUT_DIRECT_QUEUE_GENERIC_READ_COMPUTE_QUEUE_ACCESSIBLE = 31,
}
