// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.5
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE"]/*' />
public enum D3D12_STATE_SUBOBJECT_TYPE
{
    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_STATE_OBJECT_CONFIG"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_STATE_OBJECT_CONFIG = 0,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE = 1,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE = 2,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_NODE_MASK"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_NODE_MASK = 3,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY = 5,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION = 6,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 7,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DXIL_SUBOBJECT_TO_EXPORTS_ASSOCIATION"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DXIL_SUBOBJECT_TO_EXPORTS_ASSOCIATION = 8,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG = 9,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG = 10,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP = 11,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG1"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG1 = 12,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_WORK_GRAPH"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_WORK_GRAPH = 13,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_STREAM_OUTPUT"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_STREAM_OUTPUT = 14,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_BLEND"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_BLEND = 15,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_MASK"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_MASK = 16,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_RASTERIZER"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_RASTERIZER = 17,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL = 18,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_INPUT_LAYOUT"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_INPUT_LAYOUT = 19,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_IB_STRIP_CUT_VALUE"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_IB_STRIP_CUT_VALUE = 20,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_PRIMITIVE_TOPOLOGY"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_PRIMITIVE_TOPOLOGY = 21,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_RENDER_TARGET_FORMATS"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_RENDER_TARGET_FORMATS = 22,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL_FORMAT"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL_FORMAT = 23,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_DESC"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_SAMPLE_DESC = 24,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_FLAGS"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_FLAGS = 26,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL1"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL1 = 27,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_VIEW_INSTANCING"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_VIEW_INSTANCING = 28,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_GENERIC_PROGRAM"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_GENERIC_PROGRAM = 29,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL2"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL2 = 30,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_SERIALIZED_ROOT_SIGNATURE"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_SERIALIZED_ROOT_SIGNATURE = 31,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_LOCAL_SERIALIZED_ROOT_SIGNATURE"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_LOCAL_SERIALIZED_ROOT_SIGNATURE = 32,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_COMPILER_EXISITING_COLLECTION"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_COMPILER_EXISITING_COLLECTION = 33,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION_BY_KEY"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION_BY_KEY = 36,

    /// <include file='D3D12_STATE_SUBOBJECT_TYPE.xml' path='doc/member[@name="D3D12_STATE_SUBOBJECT_TYPE.D3D12_STATE_SUBOBJECT_TYPE_MAX_VALID"]/*' />
    D3D12_STATE_SUBOBJECT_TYPE_MAX_VALID = (D3D12_STATE_SUBOBJECT_TYPE_EXISTING_COLLECTION_BY_KEY + 1),
}
