// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.616.0
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX"]/*' />
public enum D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX
{
    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_TRANSPARENT = -1,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_OPAQUE = -2,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_TRANSPARENT = -3,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX.D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_SPECIAL_INDEX_FULLY_UNKNOWN_OPAQUE = -4,
}
