// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_STATE"]/*' />
public enum D3D12_RAYTRACING_OPACITY_MICROMAP_STATE
{
    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_TRANSPARENT"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_TRANSPARENT = 0,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_OPAQUE"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_OPAQUE = 1,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_UNKNOWN_TRANSPARENT"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_UNKNOWN_TRANSPARENT = 2,

    /// <include file='D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.xml' path='doc/member[@name="D3D12_RAYTRACING_OPACITY_MICROMAP_STATE.D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_UNKNOWN_OPAQUE"]/*' />
    D3D12_RAYTRACING_OPACITY_MICROMAP_STATE_UNKNOWN_OPAQUE = 3,
}
