// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API"]/*' />
public enum D3D12_MARKER_API
{
    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_SETMARKER"]/*' />
    D3D12_MARKER_API_SETMARKER = 0,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_BEGINEVENT"]/*' />
    D3D12_MARKER_API_BEGINEVENT = 1,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ENDEVENT"]/*' />
    D3D12_MARKER_API_ENDEVENT = 2,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DRAWINSTANCED"]/*' />
    D3D12_MARKER_API_DRAWINSTANCED = 3,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DRAWINDEXEDINSTANCED"]/*' />
    D3D12_MARKER_API_DRAWINDEXEDINSTANCED = 4,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_EXECUTEINDIRECT"]/*' />
    D3D12_MARKER_API_EXECUTEINDIRECT = 5,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DISPATCH"]/*' />
    D3D12_MARKER_API_DISPATCH = 6,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_COPYBUFFERREGION"]/*' />
    D3D12_MARKER_API_COPYBUFFERREGION = 7,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_COPYTEXTUREREGION"]/*' />
    D3D12_MARKER_API_COPYTEXTUREREGION = 8,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_COPYRESOURCE"]/*' />
    D3D12_MARKER_API_COPYRESOURCE = 9,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_COPYTILES"]/*' />
    D3D12_MARKER_API_COPYTILES = 10,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVESUBRESOURCE"]/*' />
    D3D12_MARKER_API_RESOLVESUBRESOURCE = 11,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_CLEARRENDERTARGETVIEW"]/*' />
    D3D12_MARKER_API_CLEARRENDERTARGETVIEW = 12,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_CLEARUNORDEREDACCESSVIEW"]/*' />
    D3D12_MARKER_API_CLEARUNORDEREDACCESSVIEW = 13,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_CLEARDEPTHSTENCILVIEW"]/*' />
    D3D12_MARKER_API_CLEARDEPTHSTENCILVIEW = 14,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOURCEBARRIER"]/*' />
    D3D12_MARKER_API_RESOURCEBARRIER = 15,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_EXECUTEBUNDLE"]/*' />
    D3D12_MARKER_API_EXECUTEBUNDLE = 16,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_PRESENT"]/*' />
    D3D12_MARKER_API_PRESENT = 17,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVEQUERYDATA"]/*' />
    D3D12_MARKER_API_RESOLVEQUERYDATA = 18,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_BEGINSUBMISSION"]/*' />
    D3D12_MARKER_API_BEGINSUBMISSION = 19,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ENDSUBMISSION"]/*' />
    D3D12_MARKER_API_ENDSUBMISSION = 20,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DECODEFRAME"]/*' />
    D3D12_MARKER_API_DECODEFRAME = 21,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_PROCESSFRAMES"]/*' />
    D3D12_MARKER_API_PROCESSFRAMES = 22,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ATOMICCOPYBUFFERUINT"]/*' />
    D3D12_MARKER_API_ATOMICCOPYBUFFERUINT = 23,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ATOMICCOPYBUFFERUINT64"]/*' />
    D3D12_MARKER_API_ATOMICCOPYBUFFERUINT64 = 24,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVESUBRESOURCEREGION"]/*' />
    D3D12_MARKER_API_RESOLVESUBRESOURCEREGION = 25,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_WRITEBUFFERIMMEDIATE"]/*' />
    D3D12_MARKER_API_WRITEBUFFERIMMEDIATE = 26,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DECODEFRAME1"]/*' />
    D3D12_MARKER_API_DECODEFRAME1 = 27,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_SETPROTECTEDRESOURCESESSION"]/*' />
    D3D12_MARKER_API_SETPROTECTEDRESOURCESESSION = 28,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DECODEFRAME2"]/*' />
    D3D12_MARKER_API_DECODEFRAME2 = 29,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_PROCESSFRAMES1"]/*' />
    D3D12_MARKER_API_PROCESSFRAMES1 = 30,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_BUILDRAYTRACINGACCELERATIONSTRUCTURE"]/*' />
    D3D12_MARKER_API_BUILDRAYTRACINGACCELERATIONSTRUCTURE = 31,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO"]/*' />
    D3D12_MARKER_API_EMITRAYTRACINGACCELERATIONSTRUCTUREPOSTBUILDINFO = 32,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_COPYRAYTRACINGACCELERATIONSTRUCTURE"]/*' />
    D3D12_MARKER_API_COPYRAYTRACINGACCELERATIONSTRUCTURE = 33,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DISPATCHRAYS"]/*' />
    D3D12_MARKER_API_DISPATCHRAYS = 34,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_INITIALIZEMETACOMMAND"]/*' />
    D3D12_MARKER_API_INITIALIZEMETACOMMAND = 35,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_EXECUTEMETACOMMAND"]/*' />
    D3D12_MARKER_API_EXECUTEMETACOMMAND = 36,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ESTIMATEMOTION"]/*' />
    D3D12_MARKER_API_ESTIMATEMOTION = 37,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVEMOTIONVECTORHEAP"]/*' />
    D3D12_MARKER_API_RESOLVEMOTIONVECTORHEAP = 38,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_SETPIPELINESTATE1"]/*' />
    D3D12_MARKER_API_SETPIPELINESTATE1 = 39,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_INITIALIZEEXTENSIONCOMMAND"]/*' />
    D3D12_MARKER_API_INITIALIZEEXTENSIONCOMMAND = 40,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_EXECUTEEXTENSIONCOMMAND"]/*' />
    D3D12_MARKER_API_EXECUTEEXTENSIONCOMMAND = 41,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DISPATCHMESH"]/*' />
    D3D12_MARKER_API_DISPATCHMESH = 42,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ENCODEFRAME"]/*' />
    D3D12_MARKER_API_ENCODEFRAME = 43,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA"]/*' />
    D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA = 44,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_BARRIER"]/*' />
    D3D12_MARKER_API_BARRIER = 45,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_BEGIN_COMMAND_LIST"]/*' />
    D3D12_MARKER_API_BEGIN_COMMAND_LIST = 46,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_DISPATCHGRAPH"]/*' />
    D3D12_MARKER_API_DISPATCHGRAPH = 47,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_SETPROGRAM"]/*' />
    D3D12_MARKER_API_SETPROGRAM = 48,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_ENCODEFRAME1"]/*' />
    D3D12_MARKER_API_ENCODEFRAME1 = 49,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA1"]/*' />
    D3D12_MARKER_API_RESOLVEENCODEROUTPUTMETADATA1 = 50,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_RESOLVEINPUTPARAMLAYOUT"]/*' />
    D3D12_MARKER_API_RESOLVEINPUTPARAMLAYOUT = 51,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_PROCESSFRAMES2"]/*' />
    D3D12_MARKER_API_PROCESSFRAMES2 = 52,

    /// <include file='D3D12_MARKER_API.xml' path='doc/member[@name="D3D12_MARKER_API.D3D12_MARKER_API_SET_WORK_GRAPH_MAXIMUM_GPU_INPUT_RECORDS"]/*' />
    D3D12_MARKER_API_SET_WORK_GRAPH_MAXIMUM_GPU_INPUT_RECORDS = 53,
}
