// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.618.5
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.xml' path='doc/member[@name="D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS"]/*' />
public enum D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS
{
    /// <include file='D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.xml' path='doc/member[@name="D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_UNKNOWN"]/*' />
    D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_UNKNOWN = 1,

    /// <include file='D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.xml' path='doc/member[@name="D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_USED"]/*' />
    D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_USED = 2,

    /// <include file='D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.xml' path='doc/member[@name="D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_IGNORED"]/*' />
    D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_IGNORED = 3,

    /// <include file='D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.xml' path='doc/member[@name="D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_STATUS.D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_NOT_SPECIFIED"]/*' />
    D3D12_APPLICATION_SPECIFIC_DRIVER_BLOB_NOT_SPECIFIED = 4,
}
