// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/dwrite.h in the Windows SDK for Windows 10.0.19041.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop
{
    [NativeTypeName("int")]
    public enum DWRITE_FONT_FEATURE_TAG : uint
    {
        DWRITE_FONT_FEATURE_TAG_ALTERNATIVE_FRACTIONS = (((uint)((byte)((byte)('c'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('f'))) << 8) | (uint)((byte)((byte)('a')))),
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS_FROM_CAPITALS = (((uint)((byte)((byte)('c'))) << 24) | ((uint)((byte)((byte)('p'))) << 16) | ((uint)((byte)((byte)('2'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS_FROM_CAPITALS = (((uint)((byte)((byte)('c'))) << 24) | ((uint)((byte)((byte)('s'))) << 16) | ((uint)((byte)((byte)('2'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_ALTERNATES = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CASE_SENSITIVE_FORMS = (((uint)((byte)((byte)('e'))) << 24) | ((uint)((byte)((byte)('s'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_GLYPH_COMPOSITION_DECOMPOSITION = (((uint)((byte)((byte)('p'))) << 24) | ((uint)((byte)((byte)('m'))) << 16) | ((uint)((byte)((byte)('c'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_LIGATURES = (((uint)((byte)((byte)('g'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('l'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CAPITAL_SPACING = (((uint)((byte)((byte)('p'))) << 24) | ((uint)((byte)((byte)('s'))) << 16) | ((uint)((byte)((byte)('p'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_SWASH = (((uint)((byte)((byte)('h'))) << 24) | ((uint)((byte)((byte)('w'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_CURSIVE_POSITIONING = (((uint)((byte)((byte)('s'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('u'))) << 8) | (uint)((byte)((byte)('c')))),
        DWRITE_FONT_FEATURE_TAG_DEFAULT = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('f'))) << 8) | (uint)((byte)((byte)('d')))),
        DWRITE_FONT_FEATURE_TAG_DISCRETIONARY_LIGATURES = (((uint)((byte)((byte)('g'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('l'))) << 8) | (uint)((byte)((byte)('d')))),
        DWRITE_FONT_FEATURE_TAG_EXPERT_FORMS = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('p'))) << 16) | ((uint)((byte)((byte)('x'))) << 8) | (uint)((byte)((byte)('e')))),
        DWRITE_FONT_FEATURE_TAG_FRACTIONS = (((uint)((byte)((byte)('c'))) << 24) | ((uint)((byte)((byte)('a'))) << 16) | ((uint)((byte)((byte)('r'))) << 8) | (uint)((byte)((byte)('f')))),
        DWRITE_FONT_FEATURE_TAG_FULL_WIDTH = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('f')))),
        DWRITE_FONT_FEATURE_TAG_HALF_FORMS = (((uint)((byte)((byte)('f'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HALANT_FORMS = (((uint)((byte)((byte)('n'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_HALF_WIDTH = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_FORMS = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('s'))) << 16) | ((uint)((byte)((byte)('i'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HORIZONTAL_KANA_ALTERNATES = (((uint)((byte)((byte)('a'))) << 24) | ((uint)((byte)((byte)('n'))) << 16) | ((uint)((byte)((byte)('k'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_LIGATURES = (((uint)((byte)((byte)('g'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('l'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HALF_WIDTH = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_HOJO_KANJI_FORMS = (((uint)((byte)((byte)('o'))) << 24) | ((uint)((byte)((byte)('j'))) << 16) | ((uint)((byte)((byte)('o'))) << 8) | (uint)((byte)((byte)('h')))),
        DWRITE_FONT_FEATURE_TAG_JIS04_FORMS = (((uint)((byte)((byte)('4'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('p'))) << 8) | (uint)((byte)((byte)('j')))),
        DWRITE_FONT_FEATURE_TAG_JIS78_FORMS = (((uint)((byte)((byte)('8'))) << 24) | ((uint)((byte)((byte)('7'))) << 16) | ((uint)((byte)((byte)('p'))) << 8) | (uint)((byte)((byte)('j')))),
        DWRITE_FONT_FEATURE_TAG_JIS83_FORMS = (((uint)((byte)((byte)('3'))) << 24) | ((uint)((byte)((byte)('8'))) << 16) | ((uint)((byte)((byte)('p'))) << 8) | (uint)((byte)((byte)('j')))),
        DWRITE_FONT_FEATURE_TAG_JIS90_FORMS = (((uint)((byte)((byte)('0'))) << 24) | ((uint)((byte)((byte)('9'))) << 16) | ((uint)((byte)((byte)('p'))) << 8) | (uint)((byte)((byte)('j')))),
        DWRITE_FONT_FEATURE_TAG_KERNING = (((uint)((byte)((byte)('n'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('e'))) << 8) | (uint)((byte)((byte)('k')))),
        DWRITE_FONT_FEATURE_TAG_STANDARD_LIGATURES = (((uint)((byte)((byte)('a'))) << 24) | ((uint)((byte)((byte)('g'))) << 16) | ((uint)((byte)((byte)('i'))) << 8) | (uint)((byte)((byte)('l')))),
        DWRITE_FONT_FEATURE_TAG_LINING_FIGURES = (((uint)((byte)((byte)('m'))) << 24) | ((uint)((byte)((byte)('u'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('l')))),
        DWRITE_FONT_FEATURE_TAG_LOCALIZED_FORMS = (((uint)((byte)((byte)('l'))) << 24) | ((uint)((byte)((byte)('c'))) << 16) | ((uint)((byte)((byte)('o'))) << 8) | (uint)((byte)((byte)('l')))),
        DWRITE_FONT_FEATURE_TAG_MARK_POSITIONING = (((uint)((byte)((byte)('k'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('m')))),
        DWRITE_FONT_FEATURE_TAG_MATHEMATICAL_GREEK = (((uint)((byte)((byte)('k'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('g'))) << 8) | (uint)((byte)((byte)('m')))),
        DWRITE_FONT_FEATURE_TAG_MARK_TO_MARK_POSITIONING = (((uint)((byte)((byte)('k'))) << 24) | ((uint)((byte)((byte)('m'))) << 16) | ((uint)((byte)((byte)('k'))) << 8) | (uint)((byte)((byte)('m')))),
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_ANNOTATION_FORMS = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('n')))),
        DWRITE_FONT_FEATURE_TAG_NLC_KANJI_FORMS = (((uint)((byte)((byte)('k'))) << 24) | ((uint)((byte)((byte)('c'))) << 16) | ((uint)((byte)((byte)('l'))) << 8) | (uint)((byte)((byte)('n')))),
        DWRITE_FONT_FEATURE_TAG_OLD_STYLE_FIGURES = (((uint)((byte)((byte)('m'))) << 24) | ((uint)((byte)((byte)('u'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('o')))),
        DWRITE_FONT_FEATURE_TAG_ORDINALS = (((uint)((byte)((byte)('n'))) << 24) | ((uint)((byte)((byte)('d'))) << 16) | ((uint)((byte)((byte)('r'))) << 8) | (uint)((byte)((byte)('o')))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_ALTERNATE_WIDTH = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('p')))),
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS = (((uint)((byte)((byte)('p'))) << 24) | ((uint)((byte)((byte)('a'))) << 16) | ((uint)((byte)((byte)('c'))) << 8) | (uint)((byte)((byte)('p')))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_FIGURES = (((uint)((byte)((byte)('m'))) << 24) | ((uint)((byte)((byte)('u'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('p')))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_WIDTHS = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('p')))),
        DWRITE_FONT_FEATURE_TAG_QUARTER_WIDTHS = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('q')))),
        DWRITE_FONT_FEATURE_TAG_REQUIRED_LIGATURES = (((uint)((byte)((byte)('g'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('l'))) << 8) | (uint)((byte)((byte)('r')))),
        DWRITE_FONT_FEATURE_TAG_RUBY_NOTATION_FORMS = (((uint)((byte)((byte)('y'))) << 24) | ((uint)((byte)((byte)('b'))) << 16) | ((uint)((byte)((byte)('u'))) << 8) | (uint)((byte)((byte)('r')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_ALTERNATES = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('l'))) << 16) | ((uint)((byte)((byte)('a'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SCIENTIFIC_INFERIORS = (((uint)((byte)((byte)('f'))) << 24) | ((uint)((byte)((byte)('n'))) << 16) | ((uint)((byte)((byte)('i'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS = (((uint)((byte)((byte)('p'))) << 24) | ((uint)((byte)((byte)('c'))) << 16) | ((uint)((byte)((byte)('m'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SIMPLIFIED_FORMS = (((uint)((byte)((byte)('l'))) << 24) | ((uint)((byte)((byte)('p'))) << 16) | ((uint)((byte)((byte)('m'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_1 = (((uint)((byte)((byte)('1'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_2 = (((uint)((byte)((byte)('2'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_3 = (((uint)((byte)((byte)('3'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_4 = (((uint)((byte)((byte)('4'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_5 = (((uint)((byte)((byte)('5'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_6 = (((uint)((byte)((byte)('6'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_7 = (((uint)((byte)((byte)('7'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_8 = (((uint)((byte)((byte)('8'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_9 = (((uint)((byte)((byte)('9'))) << 24) | ((uint)((byte)((byte)('0'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_10 = (((uint)((byte)((byte)('0'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_11 = (((uint)((byte)((byte)('1'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_12 = (((uint)((byte)((byte)('2'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_13 = (((uint)((byte)((byte)('3'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_14 = (((uint)((byte)((byte)('4'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_15 = (((uint)((byte)((byte)('5'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_16 = (((uint)((byte)((byte)('6'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_17 = (((uint)((byte)((byte)('7'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_18 = (((uint)((byte)((byte)('8'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_19 = (((uint)((byte)((byte)('9'))) << 24) | ((uint)((byte)((byte)('1'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_20 = (((uint)((byte)((byte)('0'))) << 24) | ((uint)((byte)((byte)('2'))) << 16) | ((uint)((byte)((byte)('s'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SUBSCRIPT = (((uint)((byte)((byte)('s'))) << 24) | ((uint)((byte)((byte)('b'))) << 16) | ((uint)((byte)((byte)('u'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SUPERSCRIPT = (((uint)((byte)((byte)('s'))) << 24) | ((uint)((byte)((byte)('p'))) << 16) | ((uint)((byte)((byte)('u'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_SWASH = (((uint)((byte)((byte)('h'))) << 24) | ((uint)((byte)((byte)('s'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('s')))),
        DWRITE_FONT_FEATURE_TAG_TITLING = (((uint)((byte)((byte)('l'))) << 24) | ((uint)((byte)((byte)('t'))) << 16) | ((uint)((byte)((byte)('i'))) << 8) | (uint)((byte)((byte)('t')))),
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_NAME_FORMS = (((uint)((byte)((byte)('m'))) << 24) | ((uint)((byte)((byte)('a'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('t')))),
        DWRITE_FONT_FEATURE_TAG_TABULAR_FIGURES = (((uint)((byte)((byte)('m'))) << 24) | ((uint)((byte)((byte)('u'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('t')))),
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_FORMS = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('a'))) << 16) | ((uint)((byte)((byte)('r'))) << 8) | (uint)((byte)((byte)('t')))),
        DWRITE_FONT_FEATURE_TAG_THIRD_WIDTHS = (((uint)((byte)((byte)('d'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('w'))) << 8) | (uint)((byte)((byte)('t')))),
        DWRITE_FONT_FEATURE_TAG_UNICASE = (((uint)((byte)((byte)('c'))) << 24) | ((uint)((byte)((byte)('i'))) << 16) | ((uint)((byte)((byte)('n'))) << 8) | (uint)((byte)((byte)('u')))),
        DWRITE_FONT_FEATURE_TAG_VERTICAL_WRITING = (((uint)((byte)((byte)('t'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('e'))) << 8) | (uint)((byte)((byte)('v')))),
        DWRITE_FONT_FEATURE_TAG_VERTICAL_ALTERNATES_AND_ROTATION = (((uint)((byte)((byte)('2'))) << 24) | ((uint)((byte)((byte)('t'))) << 16) | ((uint)((byte)((byte)('r'))) << 8) | (uint)((byte)((byte)('v')))),
        DWRITE_FONT_FEATURE_TAG_SLASHED_ZERO = (((uint)((byte)((byte)('o'))) << 24) | ((uint)((byte)((byte)('r'))) << 16) | ((uint)((byte)((byte)('e'))) << 8) | (uint)((byte)((byte)('z')))),
    }
}
