// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/dwrite.h in the Windows SDK for Windows 10.0.19041.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop
{
    [NativeTypeName("int")]
    public enum DWRITE_FONT_FEATURE_TAG : uint
    {
        DWRITE_FONT_FEATURE_TAG_ALTERNATIVE_FRACTIONS = (((uint)((byte)('c')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('f')) << 8) | (uint)((byte)('a'))),
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS_FROM_CAPITALS = (((uint)((byte)('c')) << 24) | ((uint)((byte)('p')) << 16) | ((uint)((byte)('2')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS_FROM_CAPITALS = (((uint)((byte)('c')) << 24) | ((uint)((byte)('s')) << 16) | ((uint)((byte)('2')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_ALTERNATES = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CASE_SENSITIVE_FORMS = (((uint)((byte)('e')) << 24) | ((uint)((byte)('s')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_GLYPH_COMPOSITION_DECOMPOSITION = (((uint)((byte)('p')) << 24) | ((uint)((byte)('m')) << 16) | ((uint)((byte)('c')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_LIGATURES = (((uint)((byte)('g')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('l')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CAPITAL_SPACING = (((uint)((byte)('p')) << 24) | ((uint)((byte)('s')) << 16) | ((uint)((byte)('p')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CONTEXTUAL_SWASH = (((uint)((byte)('h')) << 24) | ((uint)((byte)('w')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_CURSIVE_POSITIONING = (((uint)((byte)('s')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('u')) << 8) | (uint)((byte)('c'))),
        DWRITE_FONT_FEATURE_TAG_DEFAULT = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('f')) << 8) | (uint)((byte)('d'))),
        DWRITE_FONT_FEATURE_TAG_DISCRETIONARY_LIGATURES = (((uint)((byte)('g')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('l')) << 8) | (uint)((byte)('d'))),
        DWRITE_FONT_FEATURE_TAG_EXPERT_FORMS = (((uint)((byte)('t')) << 24) | ((uint)((byte)('p')) << 16) | ((uint)((byte)('x')) << 8) | (uint)((byte)('e'))),
        DWRITE_FONT_FEATURE_TAG_FRACTIONS = (((uint)((byte)('c')) << 24) | ((uint)((byte)('a')) << 16) | ((uint)((byte)('r')) << 8) | (uint)((byte)('f'))),
        DWRITE_FONT_FEATURE_TAG_FULL_WIDTH = (((uint)((byte)('d')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('f'))),
        DWRITE_FONT_FEATURE_TAG_HALF_FORMS = (((uint)((byte)('f')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HALANT_FORMS = (((uint)((byte)('n')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_HALF_WIDTH = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_FORMS = (((uint)((byte)('t')) << 24) | ((uint)((byte)('s')) << 16) | ((uint)((byte)('i')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HORIZONTAL_KANA_ALTERNATES = (((uint)((byte)('a')) << 24) | ((uint)((byte)('n')) << 16) | ((uint)((byte)('k')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HISTORICAL_LIGATURES = (((uint)((byte)('g')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('l')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HALF_WIDTH = (((uint)((byte)('d')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_HOJO_KANJI_FORMS = (((uint)((byte)('o')) << 24) | ((uint)((byte)('j')) << 16) | ((uint)((byte)('o')) << 8) | (uint)((byte)('h'))),
        DWRITE_FONT_FEATURE_TAG_JIS04_FORMS = (((uint)((byte)('4')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('p')) << 8) | (uint)((byte)('j'))),
        DWRITE_FONT_FEATURE_TAG_JIS78_FORMS = (((uint)((byte)('8')) << 24) | ((uint)((byte)('7')) << 16) | ((uint)((byte)('p')) << 8) | (uint)((byte)('j'))),
        DWRITE_FONT_FEATURE_TAG_JIS83_FORMS = (((uint)((byte)('3')) << 24) | ((uint)((byte)('8')) << 16) | ((uint)((byte)('p')) << 8) | (uint)((byte)('j'))),
        DWRITE_FONT_FEATURE_TAG_JIS90_FORMS = (((uint)((byte)('0')) << 24) | ((uint)((byte)('9')) << 16) | ((uint)((byte)('p')) << 8) | (uint)((byte)('j'))),
        DWRITE_FONT_FEATURE_TAG_KERNING = (((uint)((byte)('n')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('e')) << 8) | (uint)((byte)('k'))),
        DWRITE_FONT_FEATURE_TAG_STANDARD_LIGATURES = (((uint)((byte)('a')) << 24) | ((uint)((byte)('g')) << 16) | ((uint)((byte)('i')) << 8) | (uint)((byte)('l'))),
        DWRITE_FONT_FEATURE_TAG_LINING_FIGURES = (((uint)((byte)('m')) << 24) | ((uint)((byte)('u')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('l'))),
        DWRITE_FONT_FEATURE_TAG_LOCALIZED_FORMS = (((uint)((byte)('l')) << 24) | ((uint)((byte)('c')) << 16) | ((uint)((byte)('o')) << 8) | (uint)((byte)('l'))),
        DWRITE_FONT_FEATURE_TAG_MARK_POSITIONING = (((uint)((byte)('k')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('m'))),
        DWRITE_FONT_FEATURE_TAG_MATHEMATICAL_GREEK = (((uint)((byte)('k')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('g')) << 8) | (uint)((byte)('m'))),
        DWRITE_FONT_FEATURE_TAG_MARK_TO_MARK_POSITIONING = (((uint)((byte)('k')) << 24) | ((uint)((byte)('m')) << 16) | ((uint)((byte)('k')) << 8) | (uint)((byte)('m'))),
        DWRITE_FONT_FEATURE_TAG_ALTERNATE_ANNOTATION_FORMS = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('n'))),
        DWRITE_FONT_FEATURE_TAG_NLC_KANJI_FORMS = (((uint)((byte)('k')) << 24) | ((uint)((byte)('c')) << 16) | ((uint)((byte)('l')) << 8) | (uint)((byte)('n'))),
        DWRITE_FONT_FEATURE_TAG_OLD_STYLE_FIGURES = (((uint)((byte)('m')) << 24) | ((uint)((byte)('u')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('o'))),
        DWRITE_FONT_FEATURE_TAG_ORDINALS = (((uint)((byte)('n')) << 24) | ((uint)((byte)('d')) << 16) | ((uint)((byte)('r')) << 8) | (uint)((byte)('o'))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_ALTERNATE_WIDTH = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('p'))),
        DWRITE_FONT_FEATURE_TAG_PETITE_CAPITALS = (((uint)((byte)('p')) << 24) | ((uint)((byte)('a')) << 16) | ((uint)((byte)('c')) << 8) | (uint)((byte)('p'))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_FIGURES = (((uint)((byte)('m')) << 24) | ((uint)((byte)('u')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('p'))),
        DWRITE_FONT_FEATURE_TAG_PROPORTIONAL_WIDTHS = (((uint)((byte)('d')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('p'))),
        DWRITE_FONT_FEATURE_TAG_QUARTER_WIDTHS = (((uint)((byte)('d')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('q'))),
        DWRITE_FONT_FEATURE_TAG_REQUIRED_LIGATURES = (((uint)((byte)('g')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('l')) << 8) | (uint)((byte)('r'))),
        DWRITE_FONT_FEATURE_TAG_RUBY_NOTATION_FORMS = (((uint)((byte)('y')) << 24) | ((uint)((byte)('b')) << 16) | ((uint)((byte)('u')) << 8) | (uint)((byte)('r'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_ALTERNATES = (((uint)((byte)('t')) << 24) | ((uint)((byte)('l')) << 16) | ((uint)((byte)('a')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SCIENTIFIC_INFERIORS = (((uint)((byte)('f')) << 24) | ((uint)((byte)('n')) << 16) | ((uint)((byte)('i')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SMALL_CAPITALS = (((uint)((byte)('p')) << 24) | ((uint)((byte)('c')) << 16) | ((uint)((byte)('m')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SIMPLIFIED_FORMS = (((uint)((byte)('l')) << 24) | ((uint)((byte)('p')) << 16) | ((uint)((byte)('m')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_1 = (((uint)((byte)('1')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_2 = (((uint)((byte)('2')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_3 = (((uint)((byte)('3')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_4 = (((uint)((byte)('4')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_5 = (((uint)((byte)('5')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_6 = (((uint)((byte)('6')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_7 = (((uint)((byte)('7')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_8 = (((uint)((byte)('8')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_9 = (((uint)((byte)('9')) << 24) | ((uint)((byte)('0')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_10 = (((uint)((byte)('0')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_11 = (((uint)((byte)('1')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_12 = (((uint)((byte)('2')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_13 = (((uint)((byte)('3')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_14 = (((uint)((byte)('4')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_15 = (((uint)((byte)('5')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_16 = (((uint)((byte)('6')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_17 = (((uint)((byte)('7')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_18 = (((uint)((byte)('8')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_19 = (((uint)((byte)('9')) << 24) | ((uint)((byte)('1')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_STYLISTIC_SET_20 = (((uint)((byte)('0')) << 24) | ((uint)((byte)('2')) << 16) | ((uint)((byte)('s')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SUBSCRIPT = (((uint)((byte)('s')) << 24) | ((uint)((byte)('b')) << 16) | ((uint)((byte)('u')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SUPERSCRIPT = (((uint)((byte)('s')) << 24) | ((uint)((byte)('p')) << 16) | ((uint)((byte)('u')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_SWASH = (((uint)((byte)('h')) << 24) | ((uint)((byte)('s')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('s'))),
        DWRITE_FONT_FEATURE_TAG_TITLING = (((uint)((byte)('l')) << 24) | ((uint)((byte)('t')) << 16) | ((uint)((byte)('i')) << 8) | (uint)((byte)('t'))),
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_NAME_FORMS = (((uint)((byte)('m')) << 24) | ((uint)((byte)('a')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('t'))),
        DWRITE_FONT_FEATURE_TAG_TABULAR_FIGURES = (((uint)((byte)('m')) << 24) | ((uint)((byte)('u')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('t'))),
        DWRITE_FONT_FEATURE_TAG_TRADITIONAL_FORMS = (((uint)((byte)('d')) << 24) | ((uint)((byte)('a')) << 16) | ((uint)((byte)('r')) << 8) | (uint)((byte)('t'))),
        DWRITE_FONT_FEATURE_TAG_THIRD_WIDTHS = (((uint)((byte)('d')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('w')) << 8) | (uint)((byte)('t'))),
        DWRITE_FONT_FEATURE_TAG_UNICASE = (((uint)((byte)('c')) << 24) | ((uint)((byte)('i')) << 16) | ((uint)((byte)('n')) << 8) | (uint)((byte)('u'))),
        DWRITE_FONT_FEATURE_TAG_VERTICAL_WRITING = (((uint)((byte)('t')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('e')) << 8) | (uint)((byte)('v'))),
        DWRITE_FONT_FEATURE_TAG_VERTICAL_ALTERNATES_AND_ROTATION = (((uint)((byte)('2')) << 24) | ((uint)((byte)('t')) << 16) | ((uint)((byte)('r')) << 8) | (uint)((byte)('v'))),
        DWRITE_FONT_FEATURE_TAG_SLASHED_ZERO = (((uint)((byte)('o')) << 24) | ((uint)((byte)('r')) << 16) | ((uint)((byte)('e')) << 8) | (uint)((byte)('z'))),
    }
}
