// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/gdiplusenums.h in the Windows SDK for Windows 10.0.19041.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop
{
    public enum HatchStyle
    {
        HatchStyleHorizontal,
        HatchStyleVertical,
        HatchStyleForwardDiagonal,
        HatchStyleBackwardDiagonal,
        HatchStyleCross,
        HatchStyleDiagonalCross,
        HatchStyle05Percent,
        HatchStyle10Percent,
        HatchStyle20Percent,
        HatchStyle25Percent,
        HatchStyle30Percent,
        HatchStyle40Percent,
        HatchStyle50Percent,
        HatchStyle60Percent,
        HatchStyle70Percent,
        HatchStyle75Percent,
        HatchStyle80Percent,
        HatchStyle90Percent,
        HatchStyleLightDownwardDiagonal,
        HatchStyleLightUpwardDiagonal,
        HatchStyleDarkDownwardDiagonal,
        HatchStyleDarkUpwardDiagonal,
        HatchStyleWideDownwardDiagonal,
        HatchStyleWideUpwardDiagonal,
        HatchStyleLightVertical,
        HatchStyleLightHorizontal,
        HatchStyleNarrowVertical,
        HatchStyleNarrowHorizontal,
        HatchStyleDarkVertical,
        HatchStyleDarkHorizontal,
        HatchStyleDashedDownwardDiagonal,
        HatchStyleDashedUpwardDiagonal,
        HatchStyleDashedHorizontal,
        HatchStyleDashedVertical,
        HatchStyleSmallConfetti,
        HatchStyleLargeConfetti,
        HatchStyleZigZag,
        HatchStyleWave,
        HatchStyleDiagonalBrick,
        HatchStyleHorizontalBrick,
        HatchStyleWeave,
        HatchStylePlaid,
        HatchStyleDivot,
        HatchStyleDottedGrid,
        HatchStyleDottedDiamond,
        HatchStyleShingle,
        HatchStyleTrellis,
        HatchStyleSphere,
        HatchStyleSmallGrid,
        HatchStyleSmallCheckerBoard,
        HatchStyleLargeCheckerBoard,
        HatchStyleOutlinedDiamond,
        HatchStyleSolidDiamond,
        HatchStyleTotal,
        HatchStyleLargeGrid = HatchStyleCross,
        HatchStyleMin = HatchStyleHorizontal,
        HatchStyleMax = HatchStyleTotal - 1,
    }
}
