// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from um/dwrite_3.h in the Windows SDK for Windows 10.0.22621.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop.DirectX;

/// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE"]/*' />
public enum DWRITE_COLOR_COMPOSITE_MODE
{
    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_CLEAR"]/*' />
    DWRITE_COLOR_COMPOSITE_CLEAR,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SRC"]/*' />
    DWRITE_COLOR_COMPOSITE_SRC,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DEST"]/*' />
    DWRITE_COLOR_COMPOSITE_DEST,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SRC_OVER"]/*' />
    DWRITE_COLOR_COMPOSITE_SRC_OVER,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DEST_OVER"]/*' />
    DWRITE_COLOR_COMPOSITE_DEST_OVER,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SRC_IN"]/*' />
    DWRITE_COLOR_COMPOSITE_SRC_IN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DEST_IN"]/*' />
    DWRITE_COLOR_COMPOSITE_DEST_IN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SRC_OUT"]/*' />
    DWRITE_COLOR_COMPOSITE_SRC_OUT,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DEST_OUT"]/*' />
    DWRITE_COLOR_COMPOSITE_DEST_OUT,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SRC_ATOP"]/*' />
    DWRITE_COLOR_COMPOSITE_SRC_ATOP,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DEST_ATOP"]/*' />
    DWRITE_COLOR_COMPOSITE_DEST_ATOP,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_XOR"]/*' />
    DWRITE_COLOR_COMPOSITE_XOR,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_PLUS"]/*' />
    DWRITE_COLOR_COMPOSITE_PLUS,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SCREEN"]/*' />
    DWRITE_COLOR_COMPOSITE_SCREEN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_OVERLAY"]/*' />
    DWRITE_COLOR_COMPOSITE_OVERLAY,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DARKEN"]/*' />
    DWRITE_COLOR_COMPOSITE_DARKEN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_LIGHTEN"]/*' />
    DWRITE_COLOR_COMPOSITE_LIGHTEN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_COLOR_DODGE"]/*' />
    DWRITE_COLOR_COMPOSITE_COLOR_DODGE,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_COLOR_BURN"]/*' />
    DWRITE_COLOR_COMPOSITE_COLOR_BURN,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_HARD_LIGHT"]/*' />
    DWRITE_COLOR_COMPOSITE_HARD_LIGHT,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_SOFT_LIGHT"]/*' />
    DWRITE_COLOR_COMPOSITE_SOFT_LIGHT,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_DIFFERENCE"]/*' />
    DWRITE_COLOR_COMPOSITE_DIFFERENCE,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_EXCLUSION"]/*' />
    DWRITE_COLOR_COMPOSITE_EXCLUSION,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_MULTIPLY"]/*' />
    DWRITE_COLOR_COMPOSITE_MULTIPLY,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_HSL_HUE"]/*' />
    DWRITE_COLOR_COMPOSITE_HSL_HUE,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_HSL_SATURATION"]/*' />
    DWRITE_COLOR_COMPOSITE_HSL_SATURATION,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_HSL_COLOR"]/*' />
    DWRITE_COLOR_COMPOSITE_HSL_COLOR,

    /// <include file='DWRITE_COLOR_COMPOSITE_MODE.xml' path='doc/member[@name="DWRITE_COLOR_COMPOSITE_MODE.DWRITE_COLOR_COMPOSITE_HSL_LUMINOSITY"]/*' />
    DWRITE_COLOR_COMPOSITE_HSL_LUMINOSITY,
}
