// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.

// Ported from d3d12sdklayers.h in microsoft/DirectX-Headers tag v1.618.2
// Original source is Copyright © Microsoft. Licensed under the MIT license

namespace TerraFX.Interop.DirectX;

/// <include file='D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.xml' path='doc/member[@name="D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE"]/*' />
public enum D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE
{
    /// <include file='D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.xml' path='doc/member[@name="D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_DISABLED"]/*' />
    D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_DISABLED = 0,

    /// <include file='D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.xml' path='doc/member[@name="D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_WHEN_HASH_BYPASSED"]/*' />
    D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_WHEN_HASH_BYPASSED = (D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_DISABLED + 1),

    /// <include file='D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.xml' path='doc/member[@name="D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_ALL_BYTECODE"]/*' />
    D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_ALL_BYTECODE = (D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_WHEN_HASH_BYPASSED + 1),

    /// <include file='D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.xml' path='doc/member[@name="D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE.D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE_DEFAULT"]/*' />
    D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_MODE_DEFAULT = D3D12_DEBUG_DEVICE_BYTECODE_VALIDATION_WHEN_HASH_BYPASSED,
}
